Created model and migration files for behaviour and behaviour level details
uwblueprint/humane-society pull request #42
Opened 2024-10-23 00:02 UTC by vips11

## Notion ticket link
[Ticket Name](https://www.notion.so/uwblueprintexecs/Extend-Behaviours-Entity-I-10d10f3fb1dc80988716e2865f807120?pvs=4)

## Implementation description
* Added a model for `behaviour_level_details` and a migration file with up and down functions
* Updated the `behaviour` model with `parent_behaviour_id` column and created a new migration file

## Steps to test
1. Run `node migration up`
2. The new table `behaviour_level_details` should be created

## What should reviewers focus on?
* 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2024-10-23 00:22 UTC, jerry-cheng5 requested changes
Great work! Good job for figuring out the constraint stuff, I think that's the first one for this project :)

Just a few minor details to touch up on before merging. Lmk if you have any questions!

2024-10-23 00:22 UTC, jerry-cheng5 commented on backend/typescript/migrations/2024.10.22T19.38.07.create-behaviour-level-details-table.ts
> +    behaviour_id: {
there should be a foreign key here to the behaviours table

2024-10-23 00:22 UTC, jerry-cheng5 commented on backend/typescript/migrations/2024.10.22T19.38.07.create-behaviour-level-details-table.ts
> +  await sequelize.getQueryInterface().dropTable(TABLE_NAME);
I think you might need to drop the constraint too? I know things can get messy with the ordering of which you drop the constraints and the tables it is associated with.

You can play around with this, but the general success criteria is that you want to be able to run the up script and then the down script for your migration file, and the database should stay exactly the same

2024-10-23 00:22 UTC, jerry-cheng5 commented on backend/typescript/migrations/2024.10.22T19.42.10.add-behaviour-columns.ts
> +      type: DataType.INTEGER,
you should have a foreign key here to itself. something like:

    pet_id: {
      type: DataType.INTEGER,
      allowNull: false,
      references: {
        model: "pets",
        key: "id",
      },
    },

(taken from backend/typescript/migrations/2024.07.06T15.03.01.create-pet-behaviour-table.ts)

2024-10-23 00:22 UTC, jerry-cheng5 commented on backend/typescript/models/behvaiourLevelDetails.model.ts
> +  description!: string;
I think we can let description and training_instructions to be nullable.

Please change this here in the model, and also the migration file. (sorry I didn't specify this in the ticket)

2024-10-23 02:35 UTC, MinIcecream commented on backend/typescript/models/behvaiourLevelDetails.model.ts
File name has a typo

2024-10-23 02:38 UTC, MinIcecream reviewed
Yeah mostly looks good, I agree w what Jerry said

2024-10-23 02:38 UTC, MinIcecream commented on backend/typescript/models/behvaiourLevelDetails.model.ts
> +@Table({ timestamps: false, tableName: "behvaiour_level_details" })
Also misspelled here

2024-10-29 22:01 UTC, jerry-cheng5 approved these changes
Looks good! I tested it by migrating all the way down then all they way back up and it works :) 

The fields look right too!

Good work Vipasha!

2024-10-29 23:13 UTC, MinIcecream approved these changes
Looks good!

2024-10-29 23:52 UTC, merged